### ISSUE TITLE
z axis wasn't moving during print unsure if it been resolved

### ISSUE THREAD

**Issue by Smarty4life** [mUVe3D/Marlin-mUVe1DLP-Running#7]
I could only move manually never got z axis to move during printing. I gave up and am going to try again. This issue hasn't been submitted yet or reviewed to my knowledge. Using nanodlp, raspi, ramps1.4 and lcd optics.

**Comment by mUVe3D** [comment]
This isn't a firmware issue, but rather a machine configuration issue. This area is for tracking firmware bugs only. Please post your issue on the general support forum.
